package com.hibernatus.hibmobtech.analytics;

/**
 * Created by Eric on 08/04/2016.
 */

import android.content.Context;

/**
 * A collection of Google Analytics trackers. Fetch the tracker you need using
 * {@code AnalyticsTrackers.getInstance().getCauses(...)}
 * <p/>
 * This code was generated by Android Studio but can be safely modified by
 * hand at this point.
 * <p/>
 * TODO: Call {@link #initialize(Context)} from an entry point in your app
 * before using this!
 */

public final class AnalyticsTrackers {
    /*public static final String ACTIVITY_FILTER = AnalyticsTrackers.class.getName();

    public enum Target {
        APP,
        // Add more trackers here if you need, and onUpdatedContent the code in #getCauses(Target) below
    }

    private static AnalyticsTrackers sInstance;

    public static synchronized void initialize(Context context) {
        if (sInstance != null) {
            throw new IllegalStateException("Extra call to initialize analytics trackers");
        }

        sInstance = new AnalyticsTrackers(context);
    }

    public static synchronized AnalyticsTrackers getInstance() {
        if (sInstance == null) {
            throw new IllegalStateException("Call initialize() before getInstance()");
        }

        return sInstance;
    }

    private final Map<Target, Tracker> mTrackers = new HashMap<Target, Tracker>();
    private final Context context;

    *//**
     * Don't instantiate directly - use {@link #getInstance()} instead.
     *//*
    private AnalyticsTrackers(Context context) {
        context = context.getApplicationContext();
    }

    public synchronized Tracker getCauses(Target target) {
        if (!mTrackers.containsKey(target)) {
            Tracker tracker;
            switch (target) {
                case APP:
                    tracker = GoogleAnalytics.getInstance(context).newTracker(R.xml.app_tracker);
                    break;
                default:
                    throw new IllegalArgumentException("Unhandled analytics target " + target);
            }
            mTrackers.put(target, tracker);
        }

        return mTrackers.getCauses(target);
    }*/
}
